import React from "react";
import type { Metadata } from "next";

// assets
import blackBrickBackground from "public/black-brick-wall-textured-background.jpg";

export const metadata: Metadata = {
    title: "Trivia Game",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const bgStyling = {
        backgroundImage: `url(${blackBrickBackground.src})`,
        // <a href="https://www.freepik.com/free-photo/black-brick-wall-textured-background_3475675.htm#query=black%20brick%20wall&position=1&from_view=search&track=ais&uuid=b7b18b50-2020-476b-95e9-4440c4d181eb">Image by rawpixel.com</a> on Freepik
        backgroundSize: "100% 100%",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
        padding: "4vh 3vw",
    };
    return (
            <section>
                <div className="h-screen bg-cover w-[100vw]" style={bgStyling}>
                    {children}
                </div>
            </section>
    );
}
