import React from "react";
import Image from "next/image";
import type { Metadata } from "next";

// assets
import blackBrickBackground from "public/black-brick-wall-textured-background.jpg";

export const metadata: Metadata = {
    title: "Trivia Game",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <div
            style={{
                position: "relative",
                width: "100vw",
                height: "100vh",
                // padding: "4vh 3vw",
                maxWidth: "100%",
                overflow: "hidden",
            }}
        >
            <div>
                <Image
                    src={blackBrickBackground}
                    alt="black stone background"
                    placeholder="blur"
                    quality={100}
                    fill
                    sizes="100vw"
                    // objectFit="cover"
                />
            </div>
            <div style={{ position: "absolute", zIndex: 1, width: "100%", height: "100%", padding: "4vh 3vw" }}>{children}</div>
        </div>
    );
}
